spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KierenEinar/spring-config/
          search-paths:
          username:
          password:
server:
  port: 6632
eureka:
  client:
    serviceUrl:
      defaultZone: http://register-cluster02:5000/eureka, http://register-cluster01:4999/eureka, http://register-cluster03:4998/eureka
